MODEL_USE: mcan
LAYER: 6
HIDDEN_SIZE: 512
FF_SIZE: 2048
MULTI_HEAD: 8
DROPOUT_R: 0.1
FLAT_MLP_SIZE: 512
FLAT_GLIMPSES: 1
FLAT_OUT_SIZE: 1536
USE_BBOX_FEAT: False
USE_AUX_FEAT: False

# Execution
BATCH_SIZE: 64
LR_BASE: 0.00007
LR_DECAY_R: 0.2
LR_DECAY_LIST: [8, 10, 12, 14]
WARMUP_EPOCH: 2
MAX_EPOCH: 14
GRAD_NORM_CLIP: -1
GRAD_ACCU_STEPS: 1
LOSS_FUNC: ce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
WORD_EMBED_SIZE: 4096
BERT_VER: 'bert-large-uncased'
BERT_ENCODER: False
USE_BERT: True
